# Generated by Django 4.2.13 on 2024-05-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Smart', '0002_rename_max_address_sensor_mac_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='umidade_medida',
            new_name='unidade_medida',
        ),
    ]
