# Generated by Django 4.2.11 on 2024-06-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Smart', '0004_umidadedata_temperaturadata_luminosidadedata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='luminosidadedata',
            name='valor',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
